### ISSUE TITLE
Playground is not working

### ISSUE THREAD

**Issue by JanabiSoft** [unoplatform/Uno.QuickStart#10]
on the official website when I press try it live button a page with uno logo shows up in the center  and that's it, nothing else.

chrome browser Version 65.0.3325.181 (Official Build) (32-bit)
windows 7 professional service pack 1

**Comment by jeromelaban** [comment]
Thanks for your report! 

Could you open the developer console (F12) and paste here what messages are shown there ?

**Comment by JanabiSoft** [comment]
this is the errors list:

Failed to load resource: net::ERR_CONNECTION_RESET
managed-a930fc85af4542ab6c4945fcc37a365bb420f047/System.Data.dll 
Failed to load resource: net::ERR_CONNECTION_RESET
managed-a930fc85af4542ab6c4945fcc37a365bb420f047/System.Diagnostics.Debug.dll Failed to load resource: net::ERR_CONNECTION_RESET
managed-a930fc85af4542ab6c4945fcc37a365bb420f047/System.Diagnostics.StackTrace.dll Failed to load resource: net::ERR_CONNECTION_RESET
managed-a930fc85af4542ab6c4945fcc37a365bb420f047/System.dll Failed to load resource: net::ERR_CONNECTION_RESET
managed-a930fc85af4542ab6c4945fcc37a365bb420f047/System.Globalization.dll Failed to load resource: net::ERR_CONNECTION_RESET
managed-a930fc85af4542ab6c4945fcc37a365bb420f047/System.Drawing.dll Failed to load resource: net::ERR_CONNECTION_RESET
index.html:1 Uncaught (in promise) TypeError: Failed to fetch
managed-a930fc85af4542ab6c4945fcc37a365bb420f047/System.Globalization.Extensions.dll Failed to load resource: net::ERR_CONNECTION_RESET
index.html:1 Uncaught (in promise) TypeError: Failed to fetch
managed-a930fc85af4542ab6c4945fcc37a365bb420f047/System.IO.Compression.dll Failed to load resource: net::ERR_CONNECTION_RESET
5index.html:1 Uncaught (in promise) TypeError: Failed to fetch
managed-a930fc85af4542ab6c4945fcc37a365bb420f047/System.IO.dll Failed to load resource: net::ERR_CONNECTION_RESET
managed-a930fc85af4542ab6c4945fcc37a365bb420f047/System.Linq.dll Failed to load resource: net::ERR_CONNECTION_RESET
4index.html:1 Uncaught (in promise) TypeError: Failed to fetch
managed-a930fc85af4542ab6c4945fcc37a365bb420f047/System.Net.Http.dll Failed to load resource: net::ERR_CONNECTION_RESET
index.html:1 Uncaught (in promise) TypeError: Failed to fetch
managed-a930fc85af4542ab6c4945fcc37a365bb420f047/System.Numerics.dll Failed to load resource: net::ERR_CONNECTION_RESET
index.html:1 Uncaught (in promise) TypeError: Failed to fetch
managed-a930fc85af4542ab6c4945fcc37a365bb420f047/System.Numerics.Vectors.dll Failed to load resource: net::ERR_CONNECTION_RESET
index.html:1 Uncaught (in promise) TypeError: Failed to fetch
managed-a930fc85af4542ab6c4945fcc37a365bb420f047/System.Reflection.dll Failed to load resource: net::ERR_CONNECTION_RESET
managed-a930fc85af4542ab6c4945fcc37a365bb420f047/System.Resources.ResourceManager.dll Failed to load resource: net::ERR_CONNECTION_RESET
2index.html:1 Uncaught (in promise) TypeError: Failed to fetch
managed-a930fc85af4542ab6c4945fcc37a365bb420f047/System.Runtime.Serialization.dll Failed to load resource: net::ERR_CONNECTION_RESET
index.html:1 Uncaught (in promise) TypeError: Failed to fetch
managed-a930fc85af4542ab6c4945fcc37a365bb420f047/System.Runtime.Extensions.dll Failed to load resource: net::ERR_CONNECTION_RESET
managed-a930fc85af4542ab6c4945fcc37a365bb420f047/System.Runtime.Serialization.Primitives.dll Failed to load resource: net::ERR_CONNECTION_RESET
index.html:1 Uncaught (in promise) TypeError: Failed to fetch
managed-a930fc85af4542ab6c4945fcc37a365bb420f047/System.Security.Cryptography.Algorithms.dll Failed to load resource: net::ERR_CONNECTION_RESET
managed-a930fc85af4542ab6c4945fcc37a365bb420f047/System.Security.SecureString.dll Failed to load resource: net::ERR_CONNECTION_RESET
managed-a930fc85af4542ab6c4945fcc37a365bb420f047/Uno.Core.dll Failed to load resource: net::ERR_CONNECTION_RESET
managed-a930fc85af4542ab6c4945fcc37a365bb420f047/System.Xml.Linq.dll Failed to load resource: net::ERR_CONNECTION_RESET
managed-a930fc85af4542ab6c4945fcc37a365bb420f047/System.Xml.dll Failed to load resource: net::ERR_CONNECTION_RESET
managed-a930fc85af4542ab6c4945fcc37a365bb420f047/Uno.dll Failed to load resource: net::ERR_CONNECTION_RESET
6index.html:1 Uncaught (in promise) TypeError: Failed to fetch
managed-a930fc85af4542ab6c4945fcc37a365bb420f047/Uno.Equality.dll Failed to load resource: net::ERR_CONNECTION_RESET
managed-a930fc85af4542ab6c4945fcc37a365bb420f047/Uno.UI.Demo.WASM.dll Failed to load resource: net::ERR_CONNECTION_RESET
managed-a930fc85af4542ab6c4945fcc37a365bb420f047/Uno.UI.dll Failed to load resource: net::ERR_CONNECTION_RESET
index.html:1 Uncaught (in promise) TypeError: Failed to fetch
managed-a930fc85af4542ab6c4945fcc37a365bb420f047/Uno.UI.Toolkit.dll Failed to load resource: net::ERR_CONNECTION_RESET
managed-a930fc85af4542ab6c4945fcc37a365bb420f047/Uno.UI.Wasm.dll Failed to load resource: net::ERR_CONNECTION_RESET
5index.html:1 Uncaught (in promise) TypeError: Failed to fetch
managed-a930fc85af4542ab6c4945fcc37a365bb420f047/Uno.Xaml.dll Failed to load resource: net::ERR_CONNECTION_RESET
managed-a930fc85af4542ab6c4945fcc37a365bb420f047/System.ComponentModel.dll Failed to load resource: net::ERR_CONNECTION_RESET
2index.html:1 Uncaught (in promise) TypeError: Failed to fetch
managed-a930fc85af4542ab6c4945fcc37a365bb420f047/System.Collections.Immutable.dll Failed to load resource: net::ERR_CONNECTION_RESET
index.html:1 Uncaught (in promise) TypeError: Failed to fetch
managed-a930fc85af4542ab6c4945fcc37a365bb420f047/System.Console.dll Failed to load resource: net::ERR_CONNECTION_RESET
managed-a930fc85af4542ab6c4945fcc37a365bb420f047/System.Collections.dll Failed to load resource: net::ERR_CONNECTION_RESET
2index.html:1 Uncaught (in promise) TypeError: Failed to fetch
managed-a930fc85af4542ab6c4945fcc37a365bb420f047/System.Core.dll Failed to load resource: net::ERR_CONNECTION_RESET
managed-a930fc85af4542ab6c4945fcc37a365bb420f047/mscorlib.dll Failed to load resource: net::ERR_CONNECTION_RESET
index.html:1 Uncaught (in promise) TypeError: Failed to fetch

**Comment by jeromelaban** [comment]
Looks like you're having issues with the binaries themselves. Would you be behind a Symantec corporate firewall ?

**Comment by JanabiSoft** [comment]
yes I'm using the work PC which has symantec corporate firewall, but the problem even from personal laptop (using edge) still not working although I don't have firewall installed other than built in windows one

**Comment by a3atech** [comment]
on edge (win10 1803 update) the following messages shown in the console:

HTML1300: Navigation occurred.
index.html (1,1)

 CSS3121: The media query -ms-viewport has been deprecated.

 go

 launched!

 Error #1 "TypeError: Unable to get property 'toString' of undefined or null reference" executing javascript: "(function(t){document.title = t;})("Uno Playground");"

 Mono: Warning: Degraded allocation.  Consider increasing nursery-size if the warning persists.

 Mono: GC_MINOR: (Nursery full) time 136654.50ms, stw 136656.61ms promoted 2485K major size: 7904K in use: 7084K los size: 1024K in use: 47K

[object Error]: {description: "Failed to fetch", message: "Failed to fetch", number: -2147418113, stack: "TypeError: Failed to fetch at Anonymous function (http://platform.uno/Playground/Uno.UI.js:51:25) at Generator.prototype.throw (native code) at rejected (http://platform.uno/Playground/Uno.UI.js:30:42)"}

 System.Exception: Failed to fetch

 --- End of stack trace from previous location where exception was thrown ---

 Read Xaml in 00:00:00.3255999

 Mono: GC_MAJOR_SWEEP: major size: 20864K in use: 35645K

 Mono: GC_MAJOR: (LOS overflow) time 102.10ms, stw 102.40ms los size: 1024K in use: 140K

 First idle dispatch: 00:03:10.1738001

**Comment by JanabiSoft** [comment]
now it is working in edge after pressing f12 . the playgroud is working now in edge. but the business pc still not working

**Comment by jeromelaban** [comment]
This definitely looks like dll files are getting blocked. 


We'll have to address this for the playground to work better in corporate environments: https://github.com/nventive/Uno.Wasm.Bootstrap/issues/9

**Comment by ghuntley** [comment]
@JanabiSoft the playground has been redeployed with the latest. Can you please try again?

**Comment by JanabiSoft** [comment]
it is working correctly since some time, but today I'v found it very fast, keep the good work
