### ISSUE TITLE
How to program with elmish style (like Elmish.XamarinForms)?

### ISSUE THREAD

**Issue by albertwoo** [unoplatform/Uno.QuickStart#11]
There is a [GitHub project ](https://github.com/fsprojects/Elmish.XamarinForms/blob/master/README.md)which let us develop a client very elegant. Can we do that with Uno, or maybe we need create a separate project like Elmish.Uno.

**Comment by jeromelaban** [comment]
Moved to https://github.com/nventive/Uno/issues/15 as this is a general comment about Uno.
