### ISSUE TITLE
How to edit XAML using the UWP editor and how to create the event handlers?

### ISSUE THREAD

**Issue by TonyHenrique** [unoplatform/Uno.QuickStart#12]
I installed the Uno Solution Template Visual Studio Extension created a new Uno Solution,

**How to edit XAML using the UWP editor?**

![unoxaml](https://user-images.githubusercontent.com/6307623/40877416-e3c9077c-6656-11e8-918c-da74559d5747.png)
![xamlerror](https://user-images.githubusercontent.com/6307623/40877468-c64e638a-6657-11e8-8be9-9135def464fc.png)

**How to create the event handlers?**

![neweventhandler](https://user-images.githubusercontent.com/6307623/40877460-a8a04ab0-6657-11e8-8aa5-81edf163861d.png)

**Comment by jeromelaban** [comment]
In some cases it seems the editor does not pick up the proper context. Make sure your minimum API is Fall Creators Update, close all your xaml files, build the UWP head once, then reopen your XAML files.

We’re probably going to have to reach out Microsoft designer folks for that.


________________________________

**Comment by rexobias** [comment]
Maybe it's similar to this issue ...

I've created a new Uno Project, and I dont have the Designer working and when editing the XAML files it cant resolve any symbols. I tried this in 2 new projects and faced the same error everytime.

The App works in both Windows and Android, but I dont have the XAML editor working.

**Comment by carldebilly** [comment]
Are you using Resharper? Resharper's XAML completition is not working well with Uno.

**Comment by rexobias** [comment]
Well, yes I am indeed.

I will try disabling it to see how it goes then.

Thank you for this amazing work. As an UWP Developer projects like this means a lot.

Edit: It didn't worked :(

**Comment by carldebilly** [comment]
In the upper-left corner of your editor, there's a drop-down (I think Microsoft's calling it the _Platform Selector_) where you can pick your head. Make sure to select the _UWP_ head.

**Comment by rexobias** [comment]
It's selected and still I dont have the editor functional. The App works as expected.

![unoxamlerror](https://user-images.githubusercontent.com/4200647/42961764-b29904f8-8b87-11e8-9976-421defa25704.PNG)

**Comment by carldebilly** [comment]
In your screenshot, the selector is on `UnoDemo.Droid`, not the UWP head...

![image](https://user-images.githubusercontent.com/4174207/42963535-819d87e0-8b62-11e8-92a0-34942bcec85c.png)

**Comment by rexobias** [comment]
Shame on me ...

:facepalm:

it works, and with ReSharper enabled. Sorry for everything. Time to Code something with Uno!

**Comment by carldebilly** [comment]
I'll close the issue. Feel free to reopen it if you still have any problem.

Don't worry, we understand perfectly. Let's say it's because of the Visual Studio ergonomy... :-).
