### ISSUE TITLE
application from the solution template failed to compile

### ISSUE THREAD

**Issue by Moreno-Borsalino** [unoplatform/Uno.QuickStart#17]
I am using VS2017 with last updates.
I created a new app using Uno Platform Template.
All nuget packages are updated. If I build solution I get the following error :
![image](https://user-images.githubusercontent.com/31926734/44607141-a9a53900-a7ef-11e8-8662-1ba0ebf66b2d.png)

the output window in VS contains following :

1>------ Build started: Project: Oggi_In_Tv_Uno.Droid, Configuration: Debug Any CPU ------
2>------ Skipped Build: Project: Oggi_In_Tv_Uno.iOS, Configuration: Debug iPhone ------
2>Project not selected to build for this solution configuration 
3>------ Skipped Build: Project: Oggi_In_Tv_Uno.UWP, Configuration: Debug x86 ------
3>Project not selected to build for this solution configuration 
4>------ Build started: Project: Oggi_In_Tv_Uno.Wasm, Configuration: Debug Any CPU ------
4>E:\DevProjects\VisualStudio11\Oggi_In_Tv_Uno\Oggi_In_Tv_Uno\Oggi_In_Tv_Uno.Shared\App.xaml.cs(101,28,101,61): warning Uno0001: Windows.ApplicationModel.SuspendingOperation.GetDeferral() is not implemented in Uno
4>E:\DevProjects\VisualStudio11\Oggi_In_Tv_Uno\Oggi_In_Tv_Uno\Oggi_In_Tv_Uno.Shared\App.xaml.cs(59,21,59,45): warning Uno0001: Windows.ApplicationModel.Activation.LaunchActivatedEventArgs.PreviousExecutionState is not implemented in Uno
4>E:\DevProjects\VisualStudio11\Oggi_In_Tv_Uno\Oggi_In_Tv_Uno\Oggi_In_Tv_Uno.Shared\App.xaml.cs(68,17,68,37): warning Uno0001: Windows.ApplicationModel.Activation.LaunchActivatedEventArgs.PrelaunchActivated is not implemented in Uno
4>E:\DevProjects\VisualStudio11\Oggi_In_Tv_Uno\Oggi_In_Tv_Uno\Oggi_In_Tv_Uno.Shared\App.xaml.cs(103,13,103,30): warning Uno0001: Windows.ApplicationModel.SuspendingDeferral.Complete() is not implemented in Uno
4>Oggi_In_Tv_Uno.Wasm -> E:\DevProjects\VisualStudio11\Oggi_In_Tv_Uno\Oggi_In_Tv_Uno\Oggi_In_Tv_Uno.Wasm\bin\Debug\netstandard2.0\Oggi_In_Tv_Uno.Wasm.dll
4>Done building project "Oggi_In_Tv_Uno.Wasm.csproj".
1>C:\Users\Moreno\.nuget\packages\uno.sourcegenerationtasks\1.21.0\build\MonoAndroid\Uno.SourceGenerationTasks.targets(94,3): error : Project has no references.
1>C:\Users\Moreno\.nuget\packages\uno.sourcegenerationtasks\1.21.0\build\MonoAndroid\Uno.SourceGenerationTasks.targets(94,3): error : Failed to analyze project file [E:\DevProjects\VisualStudio11\Oggi_In_Tv_Uno\Oggi_In_Tv_Uno\Oggi_In_Tv_Uno.Droid\Oggi_In_Tv_Uno.Droid.csproj], the targets [Microsoft.Build.Execution.TargetResult] failed to execute.This may be due to an invalid path, such as $(SolutionDir) being used in the csproj; try using relative paths instead.This may also be related to a missing default configuration directive. Refer to the Uno.SourceGenerator Readme.md file for more details.
1>E:\DevProjects\VisualStudio11\Oggi_In_Tv_Uno\Oggi_In_Tv_Uno\Oggi_In_Tv_Uno.Shared\App.xaml.cs(31,18,31,37): error CS1061: 'App' does not contain a definition for 'InitializeComponent' and no accessible extension method 'InitializeComponent' accepting a first argument of type 'App' could be found (are you missing a using directive or an assembly reference?)
1>E:\DevProjects\VisualStudio11\Oggi_In_Tv_Uno\Oggi_In_Tv_Uno\Oggi_In_Tv_Uno.Shared\MainPage.xaml.cs(27,18,27,37): error CS1061: 'MainPage' does not contain a definition for 'InitializeComponent' and no accessible extension method 'InitializeComponent' accepting a first argument of type 'MainPage' could be found (are you missing a using directive or an assembly reference?)
1>E:\DevProjects\VisualStudio11\Oggi_In_Tv_Uno\Oggi_In_Tv_Uno\Oggi_In_Tv_Uno.Shared\App.xaml.cs(59,21,59,45): warning Uno0001: Windows.ApplicationModel.Activation.LaunchActivatedEventArgs.PreviousExecutionState is not implemented in Uno
1>E:\DevProjects\VisualStudio11\Oggi_In_Tv_Uno\Oggi_In_Tv_Uno\Oggi_In_Tv_Uno.Shared\App.xaml.cs(68,17,68,37): warning Uno0001: Windows.ApplicationModel.Activation.LaunchActivatedEventArgs.PrelaunchActivated is not implemented in Uno
1>E:\DevProjects\VisualStudio11\Oggi_In_Tv_Uno\Oggi_In_Tv_Uno\Oggi_In_Tv_Uno.Shared\App.xaml.cs(101,28,101,61): warning Uno0001: Windows.ApplicationModel.SuspendingOperation.GetDeferral() is not implemented in Uno
1>E:\DevProjects\VisualStudio11\Oggi_In_Tv_Uno\Oggi_In_Tv_Uno\Oggi_In_Tv_Uno.Shared\App.xaml.cs(103,13,103,30): warning Uno0001: Windows.ApplicationModel.SuspendingDeferral.Complete() is not implemented in Uno
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 2 skipped ==========

Any idea how to fix it ?

**Comment by Moreno-Borsalino** [comment]
I continue to experiment different solution to solve the problem but it is going to be a nightmare. I tryed 2 different scenarios. In one scenario I used vs2017.8.2 with resharper 2018.2 and I get always the error about InitializeComponent. In the second scenario I used vs 2017.7.5 with resharper 2017.2 and create the same solution and I can compile without any errors.
Is it possible that the problem is related with resharper or different Visual Studio updates ?
Any other here have the same configuration and the same results ?
But more important….how to solve the problem with last version of VS and Resharper ?

**Comment by jeromelaban** [comment]
Thanks for reporting this! Two things about this:
- Are you trying to build a cross-targeted or netstandard2.0 only library as a project dependency?
- Resharper and the InitializeComponent being reported as an error is essentially a missing VS feature when code generation is involved, and should not impact the compilation of the project.

**Comment by JimGaleForce** [comment]
Moreno: I've seen this when targeting either a Live Player device or an emulator. Try to target a physically connected device to see if it works.

**Comment by jeromelaban** [comment]
@JimGaleForce that would be very interesting, and troubling at the same time... there are possible steps to troubling. Would you be able to reproduce the same issue ?

**Comment by JimGaleForce** [comment]
Very reproducible... target physical device - no issue. Target Live Player instantiated device... get issues:
![errs2](https://user-images.githubusercontent.com/9724640/44933946-ead1a780-ad1f-11e8-8fce-bfb455e1c826.PNG)

**Comment by jeromelaban** [comment]
Got it. It must be caused by the build config for the live player that don't execute custom build steps. 

Maybe we can warn the user of that, there may be custom property defined.

**Comment by JimGaleForce** [comment]
Ideally, it works too :) what custom build steps are you referring to?

**Comment by jeromelaban** [comment]
@JimGaleForce the custom build steps that are used to generate the code from XAML files. The Live Player mode skips them.

**Comment by blackjyn** [comment]
I got the same problem too.

**Comment by Moreno-Borsalino** [comment]
I am glad to know I am not alone in this problem. But I haven’t found a solution yet. I noted only that other VS2017 installation dosen’t suffer of this problem. I suspect is something embedded in the VS configuration, or extension loaded, or something other that I don’t understand.

________________________________
Da: ZVHR El Ekhsaan <notifications@github.com>
Inviato: Sunday, October 7, 2018 6:38:06 AM
A: nventive/Uno.QuickStart
Cc: Moreno-Borsalino; Author
Oggetto: Re: [nventive/Uno.QuickStart] application from the solution template failed to compile (#17)


I got the same problem too.

**Comment by jeromelaban** [comment]
@Moreno-Borsalino this looks similar to this issue #14, could you tell me if there is a folder named `obj\debug\[any_platform]\g\XamlGeneration`, and its contents ?

**Comment by blackjyn** [comment]
I got this issue only on WASM project. The iOS and Android is fine.

![csharpuno-wasm-error](https://user-images.githubusercontent.com/6046191/46592833-9674d100-caf0-11e8-87b6-403fe38a0ec8.png)

**Comment by Moreno-Borsalino** [comment]
@jeromelaban In the wasm project I have a folder XamlCodeGenerator. I attached its contents. In the Droid project I haven't XamlGeneration folder
[XamlCodeGenerator.zip](https://github.com/nventive/Uno.QuickStart/files/2457277/XamlCodeGenerator.zip)

**Comment by jeromelaban** [comment]
@blackjyn this looks like a visual studio issue, as you're only executing the restore target. How did you open this command line window ?

**Comment by jeromelaban** [comment]
@Moreno-Borsalino if those files are generated, the build should work properly. Can you run the msbuild command line as follows `msbuild /bl yourproject.csproj` and provide me the resulting msbuild.binlog file in a private message on gitter?

**Comment by jeromelaban** [comment]
So it seems that part of the problem can be with machines built with system builder, for which there's a environment variable called `Platform`. (See [this](https://social.msdn.microsoft.com/Forums/en-US/8c158025-c48e-4ae1-9921-b8ee4f390bac/sumo-simulation-sittingduck-error?forum=roboticssimulation))

You may try and remove this variable from your machine's global environment variables:

![image](https://user-images.githubusercontent.com/5839577/46694519-15463880-cbdb-11e8-8633-f1f3ffe4b687.png)

**Comment by jeromelaban** [comment]
A more explicit message was added by https://github.com/nventive/Uno.SourceGeneration/pull/49

**Comment by blackjyn** [comment]
> @blackjyn this looks like a visual studio issue, as you're only executing the restore target. How did you open this command line window ?

how should I open CMD window? 
I'm really not convenient building from the IDE
