### ISSUE TITLE
What's the state of the project?

### ISSUE THREAD

**Issue by Joebeazelman** [unoplatform/Uno.QuickStart#19]
I just started playing with the playground and I am impressed. A cross-platform story using XAML is desperately needed. I want to know what state is this project in.  The playground looks great, but the loading appears very slow. Is there some heavy instrumentation going on in the background?  Also, now that WPF and UWP are open source, how will it affect this project.  Thanks.

**Comment by jeromelaban** [comment]
We're continuously updating the project, and WebAssembly is getting lots of improvements. If you have additional questions, don't hesitate to [join us on Gitter](https://gitter.im/uno-platform/Lobby).
