### ISSUE TITLE
Image loading

### ISSUE THREAD

**Issue by samoteph** [unoplatform/Uno.QuickStart#2]
When i try to load an image on uwp with the tag Image and a correct Source it's working (ms-appx:///Assets/image.jpg). But on Android the image is not loaded. I've imported the nuget universalimageloader and configure it in Main.cs but it is not working yet.any idea ?

**Comment by jeromelaban** [comment]
Thanks for the report! 

The assets automatic generation is not setup properly in the vsix, we'll adjust that. In the meantime, the source for the Uno.QuickStart has been fixed, and local images will show up.
