### ISSUE TITLE
Unable to build the project will the latest VS2019 for Mac

### ISSUE THREAD

**Issue by alexeystrakh** [unoplatform/Uno.QuickStart#20]
I've cloned the `Uno.QuickStart` repo and, after restoring the nugets, unable to build the project in VS2019 for Mac with the following error:

/Users/.../Uno.QuickStart/src/MyApp.iOS/MyApp.iOS.csproj(1,1): Error: Unknown MSBuild failure. Please try building the project again (MyApp.iOS)

Here is the full (re)build log generated by VS:
[uno.quickstart.compilation.failure.txt](https://github.com/nventive/Uno.QuickStart/files/3045080/uno.quickstart.compilation.failure.txt)

The `Uno.Playground` sample works fine and is compilable and buildable in the same dev environment.

Is it possible to build this project in `VS2019 for Mac`?

**Comment by jeromelaban** [comment]
I've updated this repository to the 1.43.1 templates. Could you try again with the latest master ?

**Comment by jeromelaban** [comment]
The latest update of this repo fixes the build on VS for Mac.
