### ISSUE TITLE
uno-check not found

### ISSUE THREAD

**Issue by Osiris-Team** [unoplatform/Uno.QuickStart#233]
![image](https://user-images.githubusercontent.com/59899645/176857817-d7da998b-d607-47cc-8c75-19faad55758a.png)
Was following the steps for gitpod, and already failed at step 2.
Was using crtl + shift + p to open the command pallete.

**Comment by jeromelaban** [comment]
Thanks for the report! Was there any message showing up in the vscode output windows?

**Comment by Osiris-Team** [comment]
Oh dammn no clue, thats already one month ago.

**Comment by jeromelaban** [comment]
Thanks anyways :) We'll look for it. Were you still able to move forward?

**Comment by Osiris-Team** [comment]
Nope had no clue how to fix it, thus dropped my hopes in uno.

**Comment by jeromelaban** [comment]
Thanks. It seems that .NET and/or gitpod changed paths in between versions, causing this command to fail.

If you ever want to try it again, you can run the command manually this way `~/.dotnet/tools/uno-check`. Also, just so you know, you can still build apps without having uno-check running on gitpod, as all the dependencies are already setup.

**Comment by Osiris-Team** [comment]
Ah ok thanks!

**Comment by jeromelaban** [comment]
Closed by https://github.com/unoplatform/Uno.QuickStart/pull/235
