### ISSUE TITLE
CI failures on Uno.QuickStart

### ISSUE THREAD

**Issue by ghuntley** [unoplatform/Uno.QuickStart#26]
Looks to be a configuration issue as UWP compiles fine from `master`. See https://uno-platform.visualstudio.com/Uno%20Platform/_build/results?buildId=4927 for specifics.

![image](https://user-images.githubusercontent.com/127353/58493204-c410a680-81b5-11e9-8370-5f64749e56c5.png)

**Comment by artemious7** [comment]
The UWP certificate [MyApp.UWP/MyApp.UWP_TemporaryKey.pfx](https://github.com/nventive/Uno.QuickStart/blob/master/src/MyApp.UWP/MyApp.UWP_TemporaryKey.pfx) expired in May this year. 

I tried to fix this but it didn't help.
I created a new certificate as [explained here in the docs](https://docs.microsoft.com/en-us/windows/msix/package/create-certificate-package-signing#create-a-self-signed-certificate).

The powershell commands for this project:

```
New-SelfSignedCertificate -Type Custom -Subject "CN=com.example" -KeyUsage DigitalSignature -FriendlyName "Uno.Quickstart MyApp UWP certificate" -CertStoreLocation "Cert:\CurrentUser\My" -TextExtension @("2.5.29.37={text}1.3.6.1.5.5.7.3.3", "2.5.29.19={text}")
```

This command will display the new certificate thumbprint (C302F4B94B899C21E9B136FF03493918BE82228B), which we should use in the export command: 

```
$pwd = ConvertTo-SecureString -String 1234 -Force -AsPlainText 
Export-PfxCertificate -cert "Cert:\CurrentUser\My\C302F4B94B899C21E9B136FF03493918BE82228B" -FilePath "C:\Users\User\source\repos\Uno.QuickStart\src\MyApp.UWP\MyApp.UWP_TemporaryKey.pfx" -Password $pwd
```

Then I simply disabled signing by adding the parameter `/p:AppxPackageSigningEnabled=false` to the msbuildArgs section in the YAML file. And the build was successful.
