### ISSUE TITLE
About webassembly

### ISSUE THREAD

**Issue by lokinfey** [unoplatform/Uno.QuickStart#7]
I try to build demo ios/android/uwp is ok.

But When I run in webassembly , i can load my data in list view.  

I try to build Model for show my data

`using System;
using System.Collections.Generic;
using System.Text;

namespace HiUnoApp.Shared.Model
{
    public class Video
    {
        public int VideoID { get; set; }
        public string VideoName { get; set; }
        public string Teacher { get; set; }
        public string VideoImage { get; set; }
    }

    public class VideoContent
    {
        public static Video[] GetVideoList()
        {
            var books = new Video[]
            {
                new Video { VideoID = 1, VideoName = "Vulpate", Teacher = "Futurum", VideoImage = "http://jpkc.gdou.com/wechatlive/content/img/cover/th1006402.png" },
                new Video { VideoID = 2, VideoName = "Vulpate", Teacher = "Futurum", VideoImage = "http://jpkc.gdou.com/wechatlive/content/img/cover/th1006402.png" },
                new Video { VideoID = 3, VideoName = "Vulpate", Teacher = "Futurum", VideoImage = "http://jpkc.gdou.com/wechatlive/content/img/cover/th1006402.png" }
            };

            return books;
        }
    }
}`

my xaml like this

`<Page
    x:Class="HiUnoApp.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:HiUnoApp"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:data="using:HiUnoApp.Shared.Model"
    xmlns:toolkit ="using:Uno.UI.Toolkit"
    xmlns:ios="http://uno.ui/ios"
    xmlns:android="http://uno.ui/android"
    xmlns:xamarin="http://uni.ui/xamarin"
    mc:Ignorable="d">

    <Page.Resources>

    </Page.Resources>

    <Grid Background="Black">
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto" />
            <RowDefinition Height="*" />
        </Grid.RowDefinitions>
        
        <StackPanel Margin="15,15,15,0">
            <TextBlock Text="Platform.Uno  Demo" 
                       FontSize="30" FontWeight="Bold"
                       Foreground="White" />
            <TextBlock Text="Platform.Uno" Foreground="White" />
        </StackPanel>

        <ListView Name="MyListView" Grid.Row="1" 
                  SelectionMode="None" 
                  HorizontalAlignment="Center"
                  Width="1000"
                  Margin="20" 
                  ItemsSource="{Binding}">

            <ListView.ItemTemplate>
                <DataTemplate>
                    <StackPanel Margin="8">
                        <Image Source="{Binding VideoImage}"  Width="160" Height="90" />
                        <TextBlock Text="{Binding VideoName}" Foreground="White" HorizontalAlignment="Center" />
                        <TextBlock Text="{Binding Teacher}" Foreground="White" HorizontalAlignment="Center"  />
                    </StackPanel>
                </DataTemplate>
            </ListView.ItemTemplate>
        </ListView>

    </Grid>
</Page>
`

my xaml.cs is

`using HiUnoApp.Shared.Model;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices.WindowsRuntime;
using Windows.Foundation;
using Windows.Foundation.Collections;
using Windows.UI.Xaml;
using Windows.UI.Xaml.Controls;
using Windows.UI.Xaml.Controls.Primitives;
using Windows.UI.Xaml.Data;
using Windows.UI.Xaml.Input;
using Windows.UI.Xaml.Media;
using Windows.UI.Xaml.Navigation;

// The Blank Page item template is documented at http://go.microsoft.com/fwlink/?LinkId=402352&clcid=0x409

namespace HiUnoApp
{
    /// <summary>
    /// An empty page that can be used on its own or navigated to within a Frame.
    /// </summary>
    public sealed partial class MainPage : Page
    {
        public MainPage()
        {
            this.InitializeComponent();

            DataContext =  VideoContent.GetVideoList();
        }
    }
}
`

but when i run in webassembly , it can not show my model data

![screenshot 1](https://user-images.githubusercontent.com/4607663/40110921-dc3932f0-5933-11e8-9fe5-70fb7040e747.png)

iOS/Android/UWP is okay . can you help me?

**Comment by jeromelaban** [comment]
This looks like a linker issue. Can you try adding the `[Preserve]` attribute on your `Video` class ?

**Comment by lokinfey** [comment]
@jeromelaban  thx  solve it! i write a blog about that https://blog.csdn.net/kinfey/article/details/80343309
